export const IDO_LIST = [
    {
        tokenSymbol: 'mart',
        project: "ArtMeta",
        siteUrl: 'Dice.se',
        logo: '/images/launchpad/ArtMeta/logo.svg',
        hero: '/images/launchpad/ArtMeta/hero.png',
        totalRaise: 'TBC',
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        allocationMin: 'TBD',
        allocationMax: 'TBD',
        chainId: 1,
        createdBy: "DICE",
        whitelistUrl: "www.example.com",
        whitepaperUrl: "www.example.com",
        twitterUrl: "www.example.com",
        telegramUrl: "www.example.com",
        shortDescription: "Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. In a near-future world transformed by disorder, adapt and overcome dynamically-changing battlegrounds with the help of your squad and a cutting-edge arsenal.",
        longDescription: "With support for 128 players, Battlefield™ 2042 brings unprecedented scale on vast battlegrounds. Players will take on several experiences comprising elevated versions of Conquest and Breakthrough, Battlefield™ Portal; a new community-driven platform where players can create, share and discover unexpected battles from Battlefield’s iconic past, present and future, and Battlefield™ Hazard Zone; a tense, squad-focused survival experience where every bullet, every skirmish, and every decision counts.",
        feature1Description: "Deploy deep behind enemy lines to extract intel in a high-stakes survival experience. In this battle, you only get one life, so make every bullet, every skirmish and every decision count.",
        feature1Img: "/images/launchpad/ArtMeta/feature1.png",
        feature2Description: "Change the rules of war and discover unexpected battles across the wide universe of Battlefield. Replay the reimagined classics Battlefield 1942, Battlefield: Bad Company 2, and Battlefield 3 – or deploy on these timeless maps with the modern arsenal and content of Battlefield 2042.",
        feature2Img: "/images/launchpad/ArtMeta/feature2.png",
        feature3Description: "U.S.A. and Russia stand at the brink of war. Proxy wars have waged for decades, generating experienced but displaced combat veterans. These Specialists use their skills to shape the future — a future worth fighting for.",
        feature3Img: "/images/launchpad/ArtMeta/feature3.png",
        creator1: "DICE Sweden",
        creator2: "Ripple Effect Studios",
        creator3: "EA Gothenburg",
        creator4: "Criterion Games (assisting development)",
        tier1: 10,
        tier2: 25,
        tier3: 40,
        tier4: 55,
        tier5: 70,
        tier6: 85,
        tier7: 100,
    },
    {
        tokenSymbol: 'hstr',
        project: "Highstreet",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/Highstreet/logo.svg',
        hero: '/images/launchpad/Highstreet/hero.png',
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 21370,
        allocationMin: '250',
        allocationMax: '250',
        chainId: 56,
        createdBy: "DICE",
        whitelistUrl: "www.example.com",
        whitepaperUrl: "www.example.com",
        twitterUrl: "www.example.com",
        telegramUrl: "www.example.com",
        shortDescription: "Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. In a near-future world transformed by disorder, adapt and overcome dynamically-changing battlegrounds with the help of your squad and a cutting-edge arsenal.",
        longDescription: "With support for 128 players, Battlefield™ 2042 brings unprecedented scale on vast battlegrounds. Players will take on several experiences comprising elevated versions of Conquest and Breakthrough, Battlefield™ Portal; a new community-driven platform where players can create, share and discover unexpected battles from Battlefield’s iconic past, present and future, and Battlefield™ Hazard Zone; a tense, squad-focused survival experience where every bullet, every skirmish, and every decision counts.",
        feature1Description: "Deploy deep behind enemy lines to extract intel in a high-stakes survival experience. In this battle, you only get one life, so make every bullet, every skirmish and every decision count.",
        feature1Img: "/images/launchpad/ArtMeta/feature1.png",
        feature2Description: "Change the rules of war and discover unexpected battles across the wide universe of Battlefield. Replay the reimagined classics Battlefield 1942, Battlefield: Bad Company 2, and Battlefield 3 – or deploy on these timeless maps with the modern arsenal and content of Battlefield 2042.",
        feature2Img: "/images/launchpad/ArtMeta/feature2.png",
        feature3Description: "U.S.A. and Russia stand at the brink of war. Proxy wars have waged for decades, generating experienced but displaced combat veterans. These Specialists use their skills to shape the future — a future worth fighting for.",
        feature3Img: "/images/launchpad/ArtMeta/feature3.png",
        creator1: "DICE Sweden",
        creator2: "Ripple Effect Studios",
        creator3: "EA Gothenburg",
        creator4: "Criterion Games (assisting development)",
        tier1: 10,
        tier2: 25,
        tier3: 40,
        tier4: 55,
        tier5: 70,
        tier6: 85,
        tier7: 100,
    },
    {
        tokenSymbol: 'bfwd',
        project: "BattlefieldWorld",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/BattlefieldWorld/logo.svg',
        hero: '/images/launchpad/BattlefieldWorld/hero.png',
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 10812,
        allocationMin: '250',
        allocationMax: '250',
        chainId: 137,
        createdBy: "DICE",
        whitelistUrl: "www.example.com",
        whitepaperUrl: "www.example.com",
        twitterUrl: "www.example.com",
        telegramUrl: "www.example.com",
        shortDescription: "Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. In a near-future world transformed by disorder, adapt and overcome dynamically-changing battlegrounds with the help of your squad and a cutting-edge arsenal.",
        longDescription: "With support for 128 players, Battlefield™ 2042 brings unprecedented scale on vast battlegrounds. Players will take on several experiences comprising elevated versions of Conquest and Breakthrough, Battlefield™ Portal; a new community-driven platform where players can create, share and discover unexpected battles from Battlefield’s iconic past, present and future, and Battlefield™ Hazard Zone; a tense, squad-focused survival experience where every bullet, every skirmish, and every decision counts.",
        feature1Description: "Deploy deep behind enemy lines to extract intel in a high-stakes survival experience. In this battle, you only get one life, so make every bullet, every skirmish and every decision count.",
        feature1Img: "/images/launchpad/ArtMeta/feature1.png",
        feature2Description: "Change the rules of war and discover unexpected battles across the wide universe of Battlefield. Replay the reimagined classics Battlefield 1942, Battlefield: Bad Company 2, and Battlefield 3 – or deploy on these timeless maps with the modern arsenal and content of Battlefield 2042.",
        feature2Img: "/images/launchpad/ArtMeta/feature2.png",
        feature3Description: "U.S.A. and Russia stand at the brink of war. Proxy wars have waged for decades, generating experienced but displaced combat veterans. These Specialists use their skills to shape the future — a future worth fighting for.",
        feature3Img: "/images/launchpad/ArtMeta/feature3.png",
        creator1: "DICE Sweden",
        creator2: "Ripple Effect Studios",
        creator3: "EA Gothenburg",
        creator4: "Criterion Games (assisting development)",
        tier1: 10,
        tier2: 25,
        tier3: 40,
        tier4: 55,
        tier5: 70,
        tier6: 85,
        tier7: 100,
    },
    {
        tokenSymbol: 'loch',
        project: "LeagueOfChampions",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/LeagueOfChampions/logo.svg',
        hero: '/images/launchpad/LeagueOfChampions/hero.png',
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 2137025,
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,
        createdBy: "DICE",
        whitelistUrl: "www.example.com",
        whitepaperUrl: "www.example.com",
        twitterUrl: "www.example.com",
        telegramUrl: "www.example.com",
        shortDescription: "Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. In a near-future world transformed by disorder, adapt and overcome dynamically-changing battlegrounds with the help of your squad and a cutting-edge arsenal.",
        longDescription: "With support for 128 players, Battlefield™ 2042 brings unprecedented scale on vast battlegrounds. Players will take on several experiences comprising elevated versions of Conquest and Breakthrough, Battlefield™ Portal; a new community-driven platform where players can create, share and discover unexpected battles from Battlefield’s iconic past, present and future, and Battlefield™ Hazard Zone; a tense, squad-focused survival experience where every bullet, every skirmish, and every decision counts.",
        feature1Description: "Deploy deep behind enemy lines to extract intel in a high-stakes survival experience. In this battle, you only get one life, so make every bullet, every skirmish and every decision count.",
        feature1Img: "/images/launchpad/ArtMeta/feature1.png",
        feature2Description: "Change the rules of war and discover unexpected battles across the wide universe of Battlefield. Replay the reimagined classics Battlefield 1942, Battlefield: Bad Company 2, and Battlefield 3 – or deploy on these timeless maps with the modern arsenal and content of Battlefield 2042.",
        feature2Img: "/images/launchpad/ArtMeta/feature2.png",
        feature3Description: "U.S.A. and Russia stand at the brink of war. Proxy wars have waged for decades, generating experienced but displaced combat veterans. These Specialists use their skills to shape the future — a future worth fighting for.",
        feature3Img: "/images/launchpad/ArtMeta/feature3.png",
        creator1: "DICE Sweden",
        creator2: "Ripple Effect Studios",
        creator3: "EA Gothenburg",
        creator4: "Criterion Games (assisting development)",
        tier1: 10,
        tier2: 25,
        tier3: 40,
        tier4: 55,
        tier5: 70,
        tier6: 85,
        tier7: 100,
    },
    {
        tokenSymbol: 'gccoin',
        project: "Galaxy Fight Club",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/GalaxyFightClub/logo.svg',
        hero: '/images/launchpad/GalaxyFightClub/hero.png',
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),
        totalRaise: 500000,
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",
    },
    {
        tokenSymbol: 'pact',
        project: "impactMarket",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/impactMarket/logo.svg',
        hero: '/images/launchpad/impactMarket/hero.png',
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),
        totalRaise: 500000,
        allocationMin: '300',
        allocationMax: '350',
        chainId: 56,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",
    },
    {
        tokenSymbol: 'fight',
        project: "Crypto Fight Club",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/CryptoFightClub/logo.svg',
        hero: '/images/launchpad/CryptoFightClub/hero.png',
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),
        totalRaise: 500000,
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",
    },
    {
        tokenSymbol: 'rain',
        project: "Rainmaker Games",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/RainmakerGames/logo.svg',
        hero: '/images/launchpad/RainmakerGames/hero.png',
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),
        totalRaise: 500000,
        allocationMin: '300',
        allocationMax: '350',
        chainId: 56,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",
    },
]