export const IDO_LIST = [
    {
      tokenSymbol: 'mart',
      project: "ArtMeta",
      siteUrl: 'www.example.com',
      logo: '/images/launchpad/ArtMeta/logo.png',
      hero: '/images/launchpad/ArtMeta/hero.png',      
      totalRaise: 500000,     
      launchDate: new Date('May 06, 2022 21:00:00'),
      endDate: new Date('May 06, 2022 21:00:00'),
      allocationMin: 'TBD',
      allocationMax: 'TBD',
      chainId: 1,            
    },
    {
        tokenSymbol: 'hstr',
        project: "Highstreet",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/Highstreet/logo.png',
        hero: '/images/launchpad/Highstreet/hero.png',      
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 21370,     
        allocationMin: '250',
        allocationMax: '250',
        chainId: 56,            
    },
    {
        tokenSymbol: 'bfwd',
        project: "BattlefieldWorld",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/BattlefieldWorld/logo.png',
        hero: '/images/launchpad/BattlefieldWorld/hero.png',      
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 10812,     
        allocationMin: '250',
        allocationMax: '250',
        chainId: 137,            
    },
    {
        tokenSymbol: 'loch',
        project: "LeagueOfChampions",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/LeagueOfChampions/logo.png',
        hero: '/images/launchpad/LeagueOfChampions/hero.png',      
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 2137025,     
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,            
    },
]