export const IDO_LIST = [
    {
      tokenSymbol: 'mart',
      project: "ArtMeta",
      siteUrl: 'www.example.com',
      logo: '/images/launchpad/ArtMeta/logo.svg',
      hero: '/images/launchpad/ArtMeta/hero.png',      
      totalRaise: 500000,     
      launchDate: new Date('May 06, 2022 21:00:00'),
      endDate: new Date('May 06, 2022 21:00:00'),
      allocationMin: 'TBD',
      allocationMax: 'TBD',
      chainId: 1,         
      createdBy: "DICE",
      whitelist: "www.example.com"
    },
    {
        tokenSymbol: 'hstr',
        project: "Highstreet",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/Highstreet/logo.svg',
        hero: '/images/launchpad/Highstreet/hero.png',      
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 21370,     
        allocationMin: '250',
        allocationMax: '250',
        chainId: 56,            
    },
    {
        tokenSymbol: 'bfwd',
        project: "BattlefieldWorld",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/BattlefieldWorld/logo.svg',
        hero: '/images/launchpad/BattlefieldWorld/hero.png',      
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 10812,     
        allocationMin: '250',
        allocationMax: '250',
        chainId: 137,            
    },
    {
        tokenSymbol: 'loch',
        project: "LeagueOfChampions",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/LeagueOfChampions/logo.svg',
        hero: '/images/launchpad/LeagueOfChampions/hero.png',      
        launchDate: new Date('May 06, 2022 21:00:00'),
        endDate: new Date('May 06, 2022 21:00:00'),
        totalRaise: 2137025,     
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,            
    },
    {
        tokenSymbol: 'gccoin',
        project: "Galaxy Fight Club",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/GalaxyFightClub/logo.svg',
        hero: '/images/launchpad/GalaxyFightClub/hero.png',      
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),        
        totalRaise: 500000,     
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",        
    },
    {
        tokenSymbol: 'pact',
        project: "impactMarket",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/impactMarket/logo.svg',
        hero: '/images/launchpad/impactMarket/hero.png',      
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),        
        totalRaise: 500000,     
        allocationMin: '300',
        allocationMax: '350',
        chainId: 56,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",        
    },
    {
        tokenSymbol: 'fight',
        project: "Crypto Fight Club",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/CryptoFightClub/logo.svg',
        hero: '/images/launchpad/CryptoFightClub/hero.png',      
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),        
        totalRaise: 500000,     
        allocationMin: '300',
        allocationMax: '350',
        chainId: 1,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",        
    },
    {
        tokenSymbol: 'rain',
        project: "Rainmaker Games",
        siteUrl: 'www.example.com',
        logo: '/images/launchpad/RainmakerGames/logo.svg',
        hero: '/images/launchpad/RainmakerGames/hero.png',      
        launchDate: new Date('May 06, 2021 21:00:00'),
        endDate: new Date('May 06, 2021 21:00:00'),        
        totalRaise: 500000,     
        allocationMin: '300',
        allocationMax: '350',
        chainId: 56,
        yourInvestment: 450,
        participants: 3618,
        whitelistPrice: 0.9323,
        currentPrice: 0.9323,
        ATHSinceLaunch: "+319%",        
    },
]